name: dapeng

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu
    - opencv-python
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - scipy
    - fastapi
    - uvicorn
    - psycopg2
    - requests
    - pyinstaller
