#! /bin/bash
# 車流測試,影片來源：[二仁溪_崇德橋，高雄市田寮區](https://www.youtube.com/watch?v=ZXtuVEDTAyE)
# 人流測試,影片來源：[冷水坑停車場](https://www.youtube.com/watch?v=GB64WeZZQPQ)
if [ $1 == 'car' ]
then
    if [ $# -eq 2 ] && [ $2 == 'live' ]
    then
        python object_tracker.py --flow_direction horizontal --detect_pos 360 --allow_classes car,truck,bus --video https://www.youtube.com/watch?v=ZXtuVEDTAyE
    else
        python object_tracker.py --flow_direction horizontal --detect_pos 360 --allow_classes car,truck,bus --video demo/car_demo.avi
    fi
elif [ $1 == 'person' ]
then
    if [ $# -eq 2 ] && [ $2 == 'live' ]
    then
        python object_tracker.py --flow_direction vertical --detect_pos 1500 --detect_pos_y 700 --allow_classes person --video https://www.youtube.com/watch?v=GB64WeZZQPQ
    else
        python object_tracker.py --flow_direction vertical --detect_pos 1500 --detect_pos_y 700 --allow_classes person --video demo/person_demo.avi
    fi
fi